apiVersion: apps/v1
kind: Deployment
metadata:
  name: wit-challenge-deployment
  labels:
    app: wit-challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wit-challenge
  template:
    metadata:
      labels:
        app: wit-challenge
    spec:
      containers:
      - name: wit-challenge
        image: 787632010529.dkr.ecr.eu-west-1.amazonaws.com/wit-devops-ecr:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wit-challenge-lb
spec:
  type: LoadBalancer
  selector:
    app: wit-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
